name: flutter_code_generator
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  cupertino_icons:
   


dev_dependencies:
  lints: 

flutter:
  uses-material-design: true

